# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96ce9bfa006467a82d44c859fcece89143bf9dd0069cd03d43d770fc1d26254699c7f40d9e59d389b1c2bba77fe1b9388a8a0fd1b337195bc15ea14c061f262d

test:
  secret_key_base: 1be114532219f02a88e9e5a604ded525f923ec8a4ae252bfec0c336004415054f0c02cb79cc9b0ab2c363e29828ea8c6970c9c6ebdd7566abb505ab0b765a387

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
